### ISSUE TITLE
Crystal Picnic no longer available on steam

### ISSUE THREAD

**Issue by arlen-kleinsasser** [Poussinou/FLOSS-Games-on-Steam#17]
From steam page:   'Notice: At the request of the publisher, Crystal Picnic is no longer available for sale on Steam.' 
Website is also down 
Is on sale on itch.io

**Comment by arlen-kleinsasser** [comment]
Monster RPG 2 has same issue.

**Comment by Poussinou** [comment]
Good catch for this two games 👍 I'm gonna keep them in the list with their link to Steam, but explain that it's not available anymore on the platform.

**Comment by Poussinou** [comment]
Resolved in the last commit, thanks again for your contributions !

**Comment by rammba** [comment]
Closed in [8fc55aa](https://github.com/Poussinou/FLOSS-Games-on-Steam/commit/8fc55aaaa8f24d19403e0b59befe20fd2abedd13).
