### ISSUE TITLE
Revolutionary Games' Thrive is FLOSS and available on steam

### ISSUE THREAD

**Issue by triffid** [Poussinou/FLOSS-Games-on-Steam#19]
Steam: https://store.steampowered.com/app/1779200/Thrive/

Homepage: https://revolutionarygamesstudio.com/

Github: https://github.com/Revolutionary-Games/Thrive

Apparently it's been on Steam since Nov 2021

**Comment by Poussinou** [comment]
Thanks for this amazing contribution !
