### ISSUE TITLE
add FreedroidRPG

### ISSUE THREAD

**Issue by wiki-me** [Poussinou/FLOSS-Games-on-Steam#20]
[website](https://www.freedroid.org/).
[steam](https://store.steampowered.com/app/1979930/FreedroidRPG/).

**Comment by Poussinou** [comment]
Good game, thank you !

Added in [b9c53e8](https://github.com/Poussinou/FLOSS-Games-on-Steam/commit/b9c53e84d0c12ddc2a78eb471a9950e52a90044a).
