### ISSUE TITLE
Add open source works by Blendogames

### ISSUE THREAD

**Issue by fahrstuhl** [Poussinou/FLOSS-Games-on-Steam#24]
At least these four games by Blendogames are open source:

[Gravity Bone](https://blendogames.com/gravitybone/): https://github.com/blendogames/gravitybone

[Flotilla](https://blendogames.com/flotilla/): https://github.com/blendogames/flotilla

[Thirty Flights of Loving](https://blendogames.com/thirtyflightsofloving/): https://github.com/blendogames/thirtyflightsofloving

[Quadrilateral Cowboy](https://blendogames.com/qc/): https://github.com/blendogames/quadrilateralcowboy

**Comment by Poussinou** [comment]
Hi @fahrstuhl 

Thanks for this, they were all added :)
