### ISSUE TITLE
ROTA

### ISSUE THREAD

**Issue by wiki-me** [Poussinou/FLOSS-Games-on-Steam#26]
[github](https://github.com/HarmonyHoney/ROTA)

[steam](https://store.steampowered.com/app/1993830/ROTA/)

**Comment by Poussinou** [comment]
@wiki-me Hi,

Thanks again, Do you want to become a collaborator of this repo, so you can push your own changes if you want? I would gladly welcome someone on this repo!

**Comment by wiki-me** [comment]
No thanks, i have other FOSS stuff i want to work on.

**Comment by Poussinou** [comment]
Hi @HarmonyHoney just to let you know that your game is now in this list :)

Thanks for open sourcing your game!

**Comment by HarmonyHoney** [comment]
> Hi @HarmonyHoney just to let you know that your game is now in this list :)
> 
> Thanks for open sourcing your game!

Awesome thank you! I'm stoked to be a part of this list! <3(+:
