### ISSUE TITLE
Astral Shipwright links to a fork and not the current repo associated with the steam game.

### ISSUE THREAD

**Issue by Summertime** [Poussinou/FLOSS-Games-on-Steam#31]

**Comment by Poussinou** [comment]
Good catch, thanks for pointing the mistake. It has been corrected in the last commit!

Thanks!

**Comment by rammba** [comment]
Closed in [9bf31e3](https://github.com/Poussinou/FLOSS-Games-on-Steam/commit/9bf31e316293fd1726054c9e85adf2e1a692be94).
