### ISSUE TITLE
FLOSS software on Steam

### ISSUE THREAD

**Issue by rammba** [Poussinou/FLOSS-Games-on-Steam#36]
I think we can consider adding FLOSS Steam software to the list. One example is [OBS Studio](https://store.steampowered.com/app/1905180/OBS_Studio/) which has [GitHub repository](https://github.com/obsproject/obs-studio) also.
I know that similar software is not used only on the Steam, but since it's available there, maybe we can list it here.

**Comment by Poussinou** [comment]
I also think we can add the FLOSS software available on the Steam platform. You can go ahead, or I'll do it when I have some time, which might be soon or not :/

I think we can add them directly inside the list of games, this will help people discover them :)

Another one below

## Krita
[Software on Steam](https://store.steampowered.com/app/280680/Krita/) | [Source Code](https://invent.kde.org/graphics/krita) | [Website](https://krita.org)

Krita is a powerful digital painting application, made for illustrators, game artists, concept artists, animators, comic book artists and everyone who wants to draw and paint.

**Comment by Poussinou** [comment]
Also Blender, Godot
