### ISSUE TITLE
Trigger Time

### ISSUE THREAD

**Issue by Sheph** [Poussinou/FLOSS-Games-on-Steam#9]
https://store.steampowered.com/app/512920

https://github.com/Sheph/TriggerTime

**Comment by Poussinou** [comment]
Cool game :)

It's now in the list, thanks !

**Comment by Sheph** [comment]
Cool :)

**Comment by rammba** [comment]
Closed in [e7f5d19](https://github.com/Poussinou/FLOSS-Games-on-Steam/commit/e7f5d190c035c6bfc1ec58291c18b5af0c95299d).
